# Generated by Django 3.2.16 on 2023-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230713_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ManyToManyField(to='posts.Group'),
        ),
    ]
