# Generated by Django 3.2.16 on 2023-07-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_group_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
